# Fast-DetectGPT Single Threshold - Colab Notebook

Self-contained notebook for SemEval 2026 Task A. It calibrates one Fast-DetectGPT threshold on 2000 balanced train rows and evaluates Macro F1 on the first 1000 test rows for the selected models.

## 1. Install Dependencies

In [1]:
import os
import sys
import subprocess

IS_COLAB = "COLAB_GPU" in os.environ or "google.colab" in sys.modules
print(f"Running on {'Google Colab' if IS_COLAB else 'local Python'}")

packages = [
    "accelerate",
    "bitsandbytes",
    "datasets==4.3.0",
    "huggingface_hub>=0.34.0",
    "numpy",
    "pandas",
    "pyarrow",
    "scikit-learn",
    "tqdm",
    "transformers",
]

if IS_COLAB:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])
else:
    print("If imports fail locally, run: python -m pip install " + " ".join(packages))

Running on Google Colab

## 2. Configuration

In [2]:
from pathlib import Path

DATASET_NAME = "DaniilOr/SemEval-2026-Task13"
DATASET_CONFIG = "A"

MODEL_ALIASES = {
    "CodeLlama-7b-Instruct-hf": "codellama/CodeLlama-7b-Instruct-hf",
    "Starcoder2-3b": "bigcode/starcoder2-3b",
    "deepseek-coder-1.3b-base": "deepseek-ai/deepseek-coder-1.3b-base",
    "deepseek-coder-6.7b-base": "deepseek-ai/deepseek-coder-6.7b-base",
    "Starcoder2-7b": "bigcode/starcoder2-7b",
    "Qwen2.5-Coder-3B": "Qwen/Qwen2.5-Coder-3B",
    "CodeLlama-7b-hf": "codellama/CodeLlama-7b-hf",
    "Qwen2.5-Coder-1.5B": "Qwen/Qwen2.5-Coder-1.5B",
    "falcon-7b": "tiiuae/falcon-7b",
    "Yi-Coder-9B": "01-ai/Yi-Coder-9B",
    "Qwen2.5-Coder-7B-Instruct": "Qwen/Qwen2.5-Coder-7B-Instruct",
    "Qwen2.5-Coder-3B-Instruct": "Qwen/Qwen2.5-Coder-3B-Instruct",
    "deepseek-coder-1.3b-instruct": "deepseek-ai/deepseek-coder-1.3b-instruct",
    "Qwen2.5-Coder-7B": "Qwen/Qwen2.5-Coder-7B",
    "CodeLlama-7b-Python-hf": "codellama/CodeLlama-7b-Python-hf",
    "deepseek-coder-6.7b-instruct": "deepseek-ai/deepseek-coder-6.7b-instruct",
    "Yi-Coder-9B-Chat": "01-ai/Yi-Coder-9B-Chat",
    "CodeGemma-7b": "google/codegemma-7b",
    "CodeGemma-7b-it": "google/codegemma-7b-it",
    "stable-code-3b": "stabilityai/stable-code-3b",
}

MODELS = list(MODEL_ALIASES.keys())

TRAIN_THRESHOLD_SAMPLES = 2000
TEST_SAMPLES = 1000
THRESHOLD_GRID_SIZE = 200
MAX_LENGTH = 512
SEED = 42

# Keep this True on Colab T4/L4 to reduce VRAM use. Set False if you want full fp16 loading.
USE_8BIT_ON_CUDA = True

# Set True if you want to recompute scores even when cached CSV files exist.
FORCE_RESCORE = False

OUTPUT_DIR = Path("results")
CACHE_DIR = OUTPUT_DIR / "cache"
REPORTS_DIR = OUTPUT_DIR / "reports"
OUTPUT_CSV = OUTPUT_DIR / "result.csv"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Models to evaluate: {len(MODELS)}")
print(f"Output CSV: {OUTPUT_CSV}")

Models to evaluate: 20
Output CSV: results/result.csv

## 3. Imports, Seed, Device

In [3]:
import gc
import json
import random

import numpy as np
import pandas as pd
import torch
from datasets import load_dataset
from sklearn.metrics import classification_report, f1_score
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

try:
    from transformers import BitsAndBytesConfig
except Exception:
    BitsAndBytesConfig = None

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {DEVICE}")
if DEVICE == "cuda":
    print(torch.cuda.get_device_name(0))
    print(f"VRAM allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

Device: cuda
NVIDIA A100-SXM4-40GB
VRAM allocated: 0.00 GB

## 4. Load Task A Data

In [4]:
print(f"Loading dataset {DATASET_NAME}, config {DATASET_CONFIG}...")
train_dataset = load_dataset(DATASET_NAME, DATASET_CONFIG, split="train")
test_dataset = load_dataset(DATASET_NAME, DATASET_CONFIG, split="test")

train_df = train_dataset.to_pandas().dropna(subset=["code", "label"]).copy()
test_df = test_dataset.to_pandas().dropna(subset=["code"]).head(TEST_SAMPLES).copy()

train_df["label"] = train_df["label"].astype(int)
if "label" not in test_df.columns:
    raise ValueError("The test split has no label column, so Macro F1 cannot be computed.")
test_df["label"] = test_df["label"].astype(int)

per_class = TRAIN_THRESHOLD_SAMPLES // 2
threshold_df = pd.concat([
    train_df[train_df["label"] == 0].head(per_class),
    train_df[train_df["label"] == 1].head(per_class),
]).sample(frac=1.0, random_state=SEED).reset_index(drop=True)

print("Threshold calibration rows:")
print(threshold_df["label"].value_counts().sort_index())
print("Test rows:")
print(test_df["label"].value_counts().sort_index())

Loading dataset DaniilOr/SemEval-2026-Task13, config A...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:134: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/801 [00:00<?, ?B/s]

task_a/task_a_training_set_1.parquet:   0%|          | 0.00/203M [00:00<?, ?B/s]

task_a/task_a_validation_set.parquet:   0%|          | 0.00/40.5M [00:00<?, ?B/s]

task_a/task_a_test_set_sample.parquet:   0%|          | 0.00/593k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/500000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/100000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Threshold calibration rows:
label
0    1000
1    1000
Name: count, dtype: int64
Test rows:
label
0    777
1    223
Name: count, dtype: int64

## 5. Fast-DetectGPT Single-Threshold Functions

In [5]:
def safe_model_key(model_name):
    return model_name.replace("/", "__").replace(" ", "_")


def get_sampling_discrepancy_analytic(logits_ref, logits_score, labels):
    assert logits_ref.shape[0] == 1
    assert logits_score.shape[0] == 1
    assert labels.shape[0] == 1

    if logits_ref.size(-1) != logits_score.size(-1):
        vocab_size = min(logits_ref.size(-1), logits_score.size(-1))
        logits_ref = logits_ref[:, :, :vocab_size]
        logits_score = logits_score[:, :, :vocab_size]

    labels = labels.unsqueeze(-1) if labels.ndim == logits_score.ndim - 1 else labels
    lprobs_score = torch.log_softmax(logits_score, dim=-1)
    probs_ref = torch.softmax(logits_ref, dim=-1)

    log_likelihood = lprobs_score.gather(dim=-1, index=labels).squeeze(-1)
    mean_ref = (probs_ref * lprobs_score).sum(dim=-1)
    var_ref = (probs_ref * torch.square(lprobs_score)).sum(dim=-1) - torch.square(mean_ref)

    discrepancy = (log_likelihood.sum(dim=-1) - mean_ref.sum(dim=-1)) / (var_ref.sum(dim=-1).sqrt() + 1e-8)
    return discrepancy.mean().item()


def fit_single_threshold(y_true, y_scores, grid_size):
    thresholds = np.linspace(np.min(y_scores), np.max(y_scores), grid_size)
    best_threshold = float(thresholds[0])
    best_f1 = -1.0

    for threshold in thresholds:
        preds = (y_scores > threshold).astype(int)
        f1 = f1_score(y_true, preds, average="macro")
        if f1 > best_f1:
            best_f1 = float(f1)
            best_threshold = float(threshold)

    return best_threshold, best_f1


def load_model_and_tokenizer(model_id):
    print(f"Loading tokenizer: {model_id}")
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model_kwargs = {"trust_remote_code": True}
    if DEVICE == "cuda":
        model_kwargs["device_map"] = "auto"
        model_kwargs["torch_dtype"] = torch.float16
        if USE_8BIT_ON_CUDA and BitsAndBytesConfig is not None:
            model_kwargs["quantization_config"] = BitsAndBytesConfig(load_in_8bit=True)
    else:
        model_kwargs["torch_dtype"] = torch.float32
        model_kwargs["low_cpu_mem_usage"] = True

    print(f"Loading model: {model_id}")
    model = AutoModelForCausalLM.from_pretrained(model_id, **model_kwargs)
    if DEVICE == "cpu":
        model.to(DEVICE)
    model.eval()
    if getattr(model.config, "pad_token_id", None) is None:
        model.config.pad_token_id = tokenizer.pad_token_id
    return tokenizer, model


def compute_scores(df, tokenizer, model, desc):
    scores = []

    for row in tqdm(df.to_dict("records"), total=len(df), desc=desc):
        tokenized = tokenizer(
            row["code"],
            return_tensors="pt",
            truncation=True,
            max_length=MAX_LENGTH,
            return_token_type_ids=False,
        ).to(DEVICE)

        if tokenized.input_ids.shape[1] <= 5:
            scores.append(0.0)
            continue

        labels = tokenized.input_ids[:, 1:]
        with torch.no_grad():
            try:
                logits = model(**tokenized).logits[:, :-1]
                score = get_sampling_discrepancy_analytic(logits, logits, labels)
            except Exception as exc:
                print(f"Warning: scoring failed for one row: {exc}")
                score = 0.0
        scores.append(score)

    scored_df = df[["label"]].copy()
    scored_df["discrepancy_score"] = scores
    return scored_df


def cleanup_model(tokenizer=None, model=None, model_id=None):
    """Free GPU/CPU memory AND purge the HF cache for this model to reclaim disk space."""
    if model is not None:
        del model
    if tokenizer is not None:
        del tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    # Purge HF hub cache for this model to free disk space on Colab
    if model_id is not None:
        import shutil
        hf_cache = Path.home() / ".cache" / "huggingface" / "hub"
        model_cache_name = "models--" + model_id.replace("/", "--")
        model_cache_path = hf_cache / model_cache_name
        if model_cache_path.exists():
            print(f"Purging HF cache: {model_cache_path}")
            shutil.rmtree(model_cache_path, ignore_errors=True)

## 6. Evaluate One Model

In [ ]:
def load_or_compute_scores(model_label, model_id):
    model_cache_dir = CACHE_DIR / safe_model_key(model_label)
    train_scores_path = model_cache_dir / "train_threshold_scores.csv"
    test_scores_path = model_cache_dir / "test_scores.csv"

    if not FORCE_RESCORE and train_scores_path.exists() and test_scores_path.exists():
        print(f"Using cached scores for {model_label}")
        return pd.read_csv(train_scores_path), pd.read_csv(test_scores_path)

    model_cache_dir.mkdir(parents=True, exist_ok=True)
    tokenizer, model = load_model_and_tokenizer(model_id)
    try:
        train_scores_df = compute_scores(
            threshold_df,
            tokenizer,
            model,
            desc=f"{model_label}: threshold rows",
        )
        test_scores_df = compute_scores(
            test_df,
            tokenizer,
            model,
            desc=f"{model_label}: test rows",
        )
        train_scores_df.to_csv(train_scores_path, index=False)
        test_scores_df.to_csv(test_scores_path, index=False)
        return train_scores_df, test_scores_df
    finally:
        cleanup_model(tokenizer, model, model_id=model_id)


def evaluate_model(model_label):
    model_id = MODEL_ALIASES.get(model_label, model_label)
    train_scores_df, test_scores_df = load_or_compute_scores(model_label, model_id)

    train_y = train_scores_df["label"].astype(int).to_numpy()
    train_scores = train_scores_df["discrepancy_score"].to_numpy()
    threshold, train_f1 = fit_single_threshold(train_y, train_scores, THRESHOLD_GRID_SIZE)

    test_y = test_scores_df["label"].astype(int).to_numpy()
    test_scores = test_scores_df["discrepancy_score"].to_numpy()
    test_preds = (test_scores > threshold).astype(int)
    test_f1 = float(f1_score(test_y, test_preds, average="macro"))

    report = classification_report(
        test_y,
        test_preds,
        labels=[0, 1],
        target_names=["human", "ai"],
        output_dict=True,
        zero_division=0,
    )

    report_path = REPORTS_DIR / f"{safe_model_key(model_label)}.json"
    with report_path.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    result = {
        "model": model_label,
        "model_id": model_id,
        "threshold": threshold,
        "train_macro_f1": train_f1,
        "test_macro_f1": test_f1,
        "test_human_f1": float(report["human"]["f1-score"]),
        "test_ai_f1": float(report["ai"]["f1-score"]),
        "train_rows": int(len(train_scores_df)),
        "test_rows": int(len(test_scores_df)),
        "report_path": str(report_path),
        "error": "",
    }

    print(
        f"{model_label}: threshold={threshold:.4f}, "
        f"train_macro_f1={train_f1:.4f}, test_macro_f1={test_f1:.4f}"
    )
    return result

## 7. Run All Selected Models

In [7]:
results = []
if OUTPUT_CSV.exists() and not FORCE_RESCORE:
    results = pd.read_csv(OUTPUT_CSV).to_dict("records")

completed = {
    row.get("model")
    for row in results
    if row.get("model") and not row.get("error") and pd.notna(row.get("test_macro_f1"))
}

for model_label in MODELS:
    if model_label in completed:
        print(f"Skipping completed model: {model_label}")
        continue

    try:
        result = evaluate_model(model_label)
    except Exception as exc:
        cleanup_model(model_id=MODEL_ALIASES.get(model_label, model_label))
        result = {
            "model": model_label,
            "model_id": MODEL_ALIASES.get(model_label, model_label),
            "threshold": np.nan,
            "train_macro_f1": np.nan,
            "test_macro_f1": np.nan,
            "test_human_f1": np.nan,
            "test_ai_f1": np.nan,
            "train_rows": 0,
            "test_rows": 0,
            "report_path": "",
            "error": repr(exc),
        }
        print(f"{model_label}: failed with {exc!r}")

    results.append(result)
    pd.DataFrame(results).to_csv(OUTPUT_CSV, index=False)
    print(f"Saved partial results to {OUTPUT_CSV}")

result_df = pd.DataFrame(results)
result_df.sort_values("test_macro_f1", ascending=False, na_position="last")

Loading tokenizer: codellama/CodeLlama-7b-Instruct-hf

config.json:   0%|          | 0.00/646 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.59k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

Loading model: codellama/CodeLlama-7b-Instruct-hf

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

CodeLlama-7b-Instruct-hf: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

CodeLlama-7b-Instruct-hf: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--codellama--CodeLlama-7b-Instruct-hf
CodeLlama-7b-Instruct-hf: threshold=0.3787, train_macro_f1=0.5490, test_macro_f1=0.6752
Saved partial results to results/result.csv
Loading tokenizer: bigcode/starcoder2-3b

config.json:   0%|          | 0.00/700 [00:00<?, ?B/s]

[transformers] Model config: bos_token_id must be `None` or an integer within the vocabulary (between 0 and 49151), got 50256. This may result in unexpected behavior.
[transformers] Model config: eos_token_id must be `None` or an integer within the vocabulary (between 0 and 49151), got 50256. This may result in unexpected behavior.

tokenizer_config.json:   0%|          | 0.00/7.88k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/777k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/442k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.06M [00:00<?, ?B/s]

Loading model: bigcode/starcoder2-3b

model.safetensors:   0%|          | 0.00/12.1G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/483 [00:00<?, ?it/s]

Starcoder2-3b: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Starcoder2-3b: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--bigcode--starcoder2-3b
Starcoder2-3b: threshold=1.4784, train_macro_f1=0.5394, test_macro_f1=0.6975
Saved partial results to results/result.csv
Loading tokenizer: deepseek-ai/deepseek-coder-1.3b-base

config.json:   0%|          | 0.00/631 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/793 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.37M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

Loading model: deepseek-ai/deepseek-coder-1.3b-base

pytorch_model.bin:   0%|          | 0.00/2.69G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.69G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

deepseek-coder-1.3b-base: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

deepseek-coder-1.3b-base: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--deepseek-ai--deepseek-coder-1.3b-base
deepseek-coder-1.3b-base: threshold=-1.2261, train_macro_f1=0.4988, test_macro_f1=0.5512
Saved partial results to results/result.csv
Loading tokenizer: deepseek-ai/deepseek-coder-6.7b-base

config.json:   0%|          | 0.00/632 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/793 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.37M [00:00<?, ?B/s]

Loading model: deepseek-ai/deepseek-coder-6.7b-base

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

deepseek-coder-6.7b-base: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

deepseek-coder-6.7b-base: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--deepseek-ai--deepseek-coder-6.7b-base
deepseek-coder-6.7b-base: threshold=-1.7026, train_macro_f1=0.5166, test_macro_f1=0.5098
Saved partial results to results/result.csv
Loading tokenizer: bigcode/starcoder2-7b

config.json:   0%|          | 0.00/893 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.88k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/777k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/442k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.06M [00:00<?, ?B/s]

Loading model: bigcode/starcoder2-7b

model.safetensors.index.json:   0%|          | 0.00/41.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Starcoder2-7b: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Starcoder2-7b: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--bigcode--starcoder2-7b
Starcoder2-7b: threshold=1.3094, train_macro_f1=0.5389, test_macro_f1=0.7103
Saved partial results to results/result.csv
Loading tokenizer: Qwen/Qwen2.5-Coder-3B

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.23k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Loading model: Qwen/Qwen2.5-Coder-3B

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/139 [00:00<?, ?B/s]

Qwen2.5-Coder-3B: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Qwen2.5-Coder-3B: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-3B
Qwen2.5-Coder-3B: threshold=0.5178, train_macro_f1=0.5016, test_macro_f1=0.6357
Saved partial results to results/result.csv
Loading tokenizer: codellama/CodeLlama-7b-hf

config.json:   0%|          | 0.00/637 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/749 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

Loading model: codellama/CodeLlama-7b-hf

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

CodeLlama-7b-hf: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

CodeLlama-7b-hf: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--codellama--CodeLlama-7b-hf
CodeLlama-7b-hf: threshold=0.4945, train_macro_f1=0.5598, test_macro_f1=0.7030
Saved partial results to results/result.csv
Loading tokenizer: Qwen/Qwen2.5-Coder-1.5B

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.31k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Loading model: Qwen/Qwen2.5-Coder-1.5B

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

Qwen2.5-Coder-1.5B: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Qwen2.5-Coder-1.5B: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-1.5B
Qwen2.5-Coder-1.5B: threshold=0.4228, train_macro_f1=0.4964, test_macro_f1=0.6000
Saved partial results to results/result.csv
Loading tokenizer: tiiuae/falcon-7b

config.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

configuration_falcon.py:   0%|          | 0.00/7.16k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/tiiuae/falcon-7b:
- configuration_falcon.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
WARNING:transformers_modules.tiiuae.falcon_hyphen_7b.ec89142b67d748a1865ea4451372db8313ada0d8.configuration_falcon:
WARNING: You are currently loading Falcon using legacy code contained in the model repository. Falcon has now been fully ported into the Hugging Face transformers library. For the most up-to-date and high-performance version of the Falcon model code, please update to the latest version of transformers and then load the model without the trust_remote_code=True argument.

tokenizer_config.json:   0%|          | 0.00/287 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.73M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/281 [00:00<?, ?B/s]

Loading model: tiiuae/falcon-7b

modeling_falcon.py:   0%|          | 0.00/56.9k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/tiiuae/falcon-7b:
- modeling_falcon.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json:   0%|          | 0.00/17.7k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

[transformers] You are loading your model using eetq but no linear modules were found in your model. Please double check your model architecture, or submit an issue on github if you think this is a bug.

Loading weights:   0%|          | 0/196 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

falcon-7b: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!

Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'

falcon-7b: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'
Warning: scoring failed for one row: 'FalconModel' object has no attribute 'get_head_mask'

config.json:   0%|          | 0.00/682 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.56M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/573 [00:00<?, ?B/s]

Loading model: 01-ai/Yi-Coder-9B

model.safetensors.index.json:   0%|          | 0.00/35.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/435 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Yi-Coder-9B: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Yi-Coder-9B: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--01-ai--Yi-Coder-9B
Yi-Coder-9B: threshold=0.3513, train_macro_f1=0.4761, test_macro_f1=0.5813
Saved partial results to results/result.csv
Loading tokenizer: Qwen/Qwen2.5-Coder-7B-Instruct

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Loading model: Qwen/Qwen2.5-Coder-7B-Instruct

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Qwen2.5-Coder-7B-Instruct: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Qwen2.5-Coder-7B-Instruct: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-7B-Instruct
Qwen2.5-Coder-7B-Instruct: threshold=-1.7392, train_macro_f1=0.4414, test_macro_f1=0.5391
Saved partial results to results/result.csv
Loading tokenizer: Qwen/Qwen2.5-Coder-3B-Instruct

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Loading model: Qwen/Qwen2.5-Coder-3B-Instruct

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Qwen2.5-Coder-3B-Instruct: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Qwen2.5-Coder-3B-Instruct: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-3B-Instruct
Qwen2.5-Coder-3B-Instruct: threshold=-0.9566, train_macro_f1=0.4510, test_macro_f1=0.5412
Saved partial results to results/result.csv
Loading tokenizer: deepseek-ai/deepseek-coder-1.3b-instruct

config.json:   0%|          | 0.00/631 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.87k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.37M [00:00<?, ?B/s]

Loading model: deepseek-ai/deepseek-coder-1.3b-instruct

model.safetensors:   0%|          | 0.00/2.69G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

deepseek-coder-1.3b-instruct: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

deepseek-coder-1.3b-instruct: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--deepseek-ai--deepseek-coder-1.3b-instruct
deepseek-coder-1.3b-instruct: threshold=-3.5025, train_macro_f1=0.4324, test_macro_f1=0.5038
Saved partial results to results/result.csv
Loading tokenizer: Qwen/Qwen2.5-Coder-7B

config.json:   0%|          | 0.00/668 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.31k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Loading model: Qwen/Qwen2.5-Coder-7B

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

Qwen2.5-Coder-7B: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Qwen2.5-Coder-7B: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-7B
Qwen2.5-Coder-7B: threshold=0.2923, train_macro_f1=0.5021, test_macro_f1=0.6033
Saved partial results to results/result.csv
Loading tokenizer: codellama/CodeLlama-7b-Python-hf

config.json:   0%|          | 0.00/644 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/749 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

Loading model: codellama/CodeLlama-7b-Python-hf

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

CodeLlama-7b-Python-hf: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

CodeLlama-7b-Python-hf: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--codellama--CodeLlama-7b-Python-hf
CodeLlama-7b-Python-hf: threshold=0.4464, train_macro_f1=0.5705, test_macro_f1=0.6526
Saved partial results to results/result.csv
Loading tokenizer: deepseek-ai/deepseek-coder-6.7b-instruct

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.87k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.37M [00:00<?, ?B/s]

Loading model: deepseek-ai/deepseek-coder-6.7b-instruct

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

deepseek-coder-6.7b-instruct: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

deepseek-coder-6.7b-instruct: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--deepseek-ai--deepseek-coder-6.7b-instruct
deepseek-coder-6.7b-instruct: threshold=-5.2767, train_macro_f1=0.5079, test_macro_f1=0.5032
Saved partial results to results/result.csv
Loading tokenizer: 01-ai/Yi-Coder-9B-Chat

config.json:   0%|          | 0.00/683 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.89k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Loading model: 01-ai/Yi-Coder-9B-Chat

model.safetensors.index.json:   0%|          | 0.00/35.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/435 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Yi-Coder-9B-Chat: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

Yi-Coder-9B-Chat: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--01-ai--Yi-Coder-9B-Chat
Yi-Coder-9B-Chat: threshold=-2.6150, train_macro_f1=0.4682, test_macro_f1=0.5815
Saved partial results to results/result.csv
Loading tokenizer: google/codegemma-7b
CodeGemma-7b: failed with OSError('You are trying to access a gated repo.\nMake sure to have access to it at https://huggingface.co/google/codegemma-7b.\n401 Client Error. (Request ID: Root=1-6a3bf736-6a29731408acdd57676a1824;3744b270-6748-4bff-b548-d525971995d6)\n\nCannot access gated repo for url https://huggingface.co/google/codegemma-7b/resolve/main/config.json.\nAccess to model google/codegemma-7b is restricted. You must have access to it and be authenticated to access it. Please log in.')
Saved partial results to results/result.csv
Loading tokenizer: google/codegemma-7b-it
CodeGemma-7b-it: failed with OSError('You are trying to access a gated repo.\nMake sure to have access to it at https://huggingface.co/google/codegemma-7b-it.\n401 Client Error. (Request ID: Root=1-6a3bf737-104c3c941c0983a214efbd64;310aadf1-f651-4706-bb25-ce8a20eefdcb)\n\nCannot access gated repo for url https://huggingface.co/google/codegemma-7b-it/resolve/main/config.json.\nAccess to model google/codegemma-7b-it is restricted. You must have access to it and be authenticated to access it. Please log in.')
Saved partial results to results/result.csv
Loading tokenizer: stabilityai/stable-code-3b

config.json:   0%|          | 0.00/602 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/4.76k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.47M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/441 [00:00<?, ?B/s]

Loading model: stabilityai/stable-code-3b

model.safetensors.index.json:   0%|          | 0.00/29.4k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/356 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

stable-code-3b: threshold rows:   0%|          | 0/2000 [00:00<?, ?it/s]

stable-code-3b: test rows:   0%|          | 0/1000 [00:00<?, ?it/s]

Purging HF cache: /root/.cache/huggingface/hub/models--stabilityai--stable-code-3b
stable-code-3b: threshold=1.0671, train_macro_f1=0.5500, test_macro_f1=0.7219
Saved partial results to results/result.csv

,model,model_id,threshold,train_macro_f1,test_macro_f1,test_human_f1,test_ai_f1,train_rows,test_rows,report_path,error
19,stable-code-3b,stabilityai/stable-code-3b,1.067054,0.550049,0.721869,0.889582,0.554156,2000,1000,results/reports/stable-code-3b.json,
4,Starcoder2-7b,bigcode/starcoder2-7b,1.309399,0.538881,0.710278,0.893382,0.527174,2000,1000,results/reports/Starcoder2-7b.json,
6,CodeLlama-7b-hf,codellama/CodeLlama-7b-hf,0.494543,0.559826,0.703000,0.857143,0.548857,2000,1000,results/reports/CodeLlama-7b-hf.json,
1,Starcoder2-3b,bigcode/starcoder2-3b,1.478368,0.539368,0.697471,0.890787,0.504155,2000,1000,results/reports/Starcoder2-3b.json,
0,CodeLlama-7b-Instruct-hf,codellama/CodeLlama-7b-Instruct-hf,0.378671,0.549027,0.675160,0.852523,0.497797,2000,1000,results/reports/CodeLlama-7b-Instruct-hf.json,
14,CodeLlama-7b-Python-hf,codellama/CodeLlama-7b-Python-hf,0.446392,0.570540,0.652632,0.818674,0.486590,2000,1000,results/reports/CodeLlama-7b-Python-hf.json,
5,Qwen2.5-Coder-3B,Qwen/Qwen2.5-Coder-3B,0.517823,0.501600,0.635656,0.828758,0.442553,2000,1000,results/reports/Qwen2.5-Coder-3B.json,
13,Qwen2.5-Coder-7B,Qwen/Qwen2.5-Coder-7B,0.292321,0.502078,0.603334,0.786594,0.420074,2000,1000,results/reports/Qwen2.5-Coder-7B.json,
7,Qwen2.5-Coder-1.5B,Qwen/Qwen2.5-Coder-1.5B,0.422837,0.496437,0.599985,0.790792,0.409178,2000,1000,results/reports/Qwen2.5-Coder-1.5B.json,
16,Yi-Coder-9B-Chat,01-ai/Yi-Coder-9B-Chat,-2.615038,0.468186,0.581538,0.843077,0.320000,2000,1000,results/reports/Yi-Coder-9B-Chat.json,
9,Yi-Coder-9B,01-ai/Yi-Coder-9B,0.351327,0.476091,0.581263,0.802356,0.360169,2000,1000,results/reports/Yi-Coder-9B.json,
2,deepseek-coder-1.3b-base,deepseek-ai/deepseek-coder-1.3b-base,-1.226052,0.498795,0.551152,0.712288,0.390016,2000,1000,results/reports/deepseek-coder-1.3b-base.json,
11,Qwen2.5-Coder-3B-Instruct,Qwen/Qwen2.5-Coder-3B-Instruct,-0.956560,0.451034,0.541196,0.857312,0.225080,2000,1000,results/reports/Qwen2.5-Coder-3B-Instruct.json,
10,Qwen2.5-Coder-7B-Instruct,Qwen/Qwen2.5-Coder-7B-Instruct,-1.739204,0.441366,0.539104,0.847904,0.230303,2000,1000,results/reports/Qwen2.5-Coder-7B-Instruct.json,
3,deepseek-coder-6.7b-base,deepseek-ai/deepseek-coder-6.7b-base,-1.702634,0.516627,0.509834,0.593162,0.426506,2000,1000,results/reports/deepseek-coder-6.7b-base.json,
12,deepseek-coder-1.3b-instruct,deepseek-ai/deepseek-coder-1.3b-instruct,-3.502513,0.432379,0.503756,0.801999,0.205514,2000,1000,results/reports/deepseek-coder-1.3b-instruct.json,
15,deepseek-coder-6.7b-instruct,deepseek-ai/deepseek-coder-6.7b-instruct,-5.276686,0.507948,0.503246,0.668168,0.338323,2000,1000,results/reports/deepseek-coder-6.7b-instruct.json,
8,falcon-7b,tiiuae/falcon-7b,0.000000,0.333333,0.437254,0.874508,0.000000,2000,1000,results/reports/falcon-7b.json,
17,CodeGemma-7b,google/codegemma-7b,NaN,NaN,NaN,NaN,NaN,0,0,,OSError('You are trying to access a gated repo...
18,CodeGemma-7b-it,google/codegemma-7b-it,NaN,NaN,NaN,NaN,NaN,0,0,,OSError('You are trying to access a gated repo...

## 8. Show And Download Results

In [8]:
result_df = pd.read_csv(OUTPUT_CSV)
display_cols = ["model", "threshold", "train_macro_f1", "test_macro_f1", "test_human_f1", "test_ai_f1", "error"]
display(result_df.reindex(columns=display_cols).sort_values("test_macro_f1", ascending=False, na_position="last"))

if IS_COLAB:
    from google.colab import files
    files.download(str(OUTPUT_CSV))

,model,threshold,train_macro_f1,test_macro_f1,test_human_f1,test_ai_f1,error
19,stable-code-3b,1.067054,0.550049,0.721869,0.889582,0.554156,NaN
4,Starcoder2-7b,1.309399,0.538881,0.710278,0.893382,0.527174,NaN
6,CodeLlama-7b-hf,0.494543,0.559826,0.703000,0.857143,0.548857,NaN
1,Starcoder2-3b,1.478368,0.539368,0.697471,0.890787,0.504155,NaN
0,CodeLlama-7b-Instruct-hf,0.378671,0.549027,0.675160,0.852523,0.497797,NaN
14,CodeLlama-7b-Python-hf,0.446392,0.570540,0.652632,0.818674,0.486590,NaN
5,Qwen2.5-Coder-3B,0.517823,0.501600,0.635656,0.828758,0.442553,NaN
13,Qwen2.5-Coder-7B,0.292321,0.502078,0.603334,0.786594,0.420074,NaN
7,Qwen2.5-Coder-1.5B,0.422837,0.496437,0.599985,0.790792,0.409178,NaN
16,Yi-Coder-9B-Chat,-2.615038,0.468186,0.581538,0.843077,0.320000,NaN
9,Yi-Coder-9B,0.351327,0.476091,0.581263,0.802356,0.360169,NaN
2,deepseek-coder-1.3b-base,-1.226052,0.498795,0.551152,0.712288,0.390016,NaN
11,Qwen2.5-Coder-3B-Instruct,-0.956560,0.451034,0.541196,0.857312,0.225080,NaN
10,Qwen2.5-Coder-7B-Instruct,-1.739204,0.441366,0.539104,0.847904,0.230303,NaN
3,deepseek-coder-6.7b-base,-1.702634,0.516627,0.509834,0.593162,0.426506,NaN
12,deepseek-coder-1.3b-instruct,-3.502513,0.432379,0.503756,0.801999,0.205514,NaN
15,deepseek-coder-6.7b-instruct,-5.276686,0.507948,0.503246,0.668168,0.338323,NaN
8,falcon-7b,0.000000,0.333333,0.437254,0.874508,0.000000,NaN
17,CodeGemma-7b,NaN,NaN,NaN,NaN,NaN,OSError('You are trying to access a gated repo...
18,CodeGemma-7b-it,NaN,NaN,NaN,NaN,NaN,OSError('You are trying to access a gated repo...